/** 代表美食官網 — 優先於 Wikimedia */
module.exports = [
  { match: /一蘭/, page: 'https://www.ichiran.com/' },
  { match: /一風堂|ippudo/i, page: 'https://www.ippudo.com/' },
  { match: /ShinShin|しんしん/, page: 'https://www.hakata-shinshin.com/' },
  { match: /兼虎/, page: 'https://www.menyakantora.com/' },
  { match: /ふくや|明太子/, page: 'https://www.fukuya.com/' },
  { match: /Big Man|ビッグマン/, page: 'https://www.bigman.co.jp/' },
  { match: /スターバックス|Starbucks/i, page: 'https://www.starbucks.co.jp/' },
  { match: /唐戸市場/, page: 'https://www.karatoichiba.com/' },
  { match: /華味鳥/, page: 'https://www.hanamidori.co.jp/' },
  { match: /天ぷら処ひらお|天麩羅処ひらお/, page: 'https://www.hirao-tempura.com/' },
  { match: /博多 一叶|博多一叶/, page: 'https://hakata-ichiyo.com/' },
  { match: /大砲ラーメン|大砲拉麵/, page: 'https://www.taiho-ramen.com/' },
  { match: /麺屋兼虎/, page: 'https://www.menyakantora.com/' },
  { match: /万田うどん/, page: 'https://www.manda-udon.com/' },
  { match: /麺屋ISHII|麵屋 ISHII/, page: 'https://menya-ishii.com/' },
  { match: /一双/, page: 'https://www.issho-ramen.com/' },
  { match: /もつ鍋 一慶|もつ鍋一慶/, page: 'https://www.motsunabe-ikei.com/' },
  { match: /REC COFFEE/, page: 'https://rec-coffee.com/' },
  { match: /THE ALLDAY ORTO/, page: 'https://theallday.jp/' },
  { match: /LOG KIT/, page: 'https://log-kit.com/' },
  { match: /ヒカリ.*ハンバーガー/, page: 'https://www.hikari-burger.com/' },
  { match: /長崎ちゃんぽん|四海樓/, page: 'https://www.shikaikuro.co.jp/' },
  { match: /熊本城/, page: 'https://www.municipal.kumamoto.jp/' },
  { match: /くまモン/, page: 'https://kumamon-official.jp/' },
  { match: /由布院|金鱗湖/, page: 'https://www.yufuin.gr.jp/' },
  { match: /地獄蒸し|地獄蒸/, page: 'https://www.beppu-jigoku.com/' },
  { match: /PALM BEACH/, page: 'https://palmbeach.jp/' },
  { match: /糸島.*カフェ|糸島カフェ/, page: 'https://www.itoshima-guide.jp/' },
  { match: /博多一風堂/, page: 'https://www.ippudo.com/' },
  { match: /水炊き/, page: 'https://www.hanamidori.co.jp/' },
  { match: /鰻|うなぎ|鰻重/, page: 'https://www.unagi.co.jp/' },
  { match: /寿司|鮨|すし/, page: 'https://www.sushiken.com/' },
  { match: /焼肉|焼き肉/, page: 'https://www.yakiniku-king.com/' },
  { match: /居酒屋/, page: 'https://www.torikizoku.co.jp/' },
  { match: /カステラ|長崎蛋糕/, page: 'https://www.fukusaya.com/' },
  { match: /牡蠣|かき/, page: 'https://www.kaki-ya.com/' },
  { match: /海鮮|魚介/, page: 'https://www.karatoichiba.com/' },
  { match: /チョコレート|巧克力/, page: 'https://www.menier.co.jp/' },
  { match: /パンケーキ|鬆餅/, page: 'https://www.bills-japan.com/' },
  { match: /コーヒー|咖啡/, page: 'https://www.starbucks.co.jp/' },
];
