/** 景點官網／觀光頁 — 用於 og:image */
module.exports = [
  { match: /櫛田神社|櫛田/, page: 'https://kushida-jinja.or.jp/' },
  { match: /博多キャナル|運河城|Canal/i, page: 'https://canalcity.co.jp/' },
  { match: /太宰府天満宮|太宰府天滿宮/, page: 'https://www.dazaifu.or.jp/' },
  { match: /スターバックス太宰府|隈研吾/, page: 'https://www.starbucks.co.jp/' },
  { match: /宝満宮|竈門神社/, page: 'https://www.kamadojinja.or.jp/' },
  { match: /宮地嶽神社/, page: 'https://www.miyajidake.or.jp/' },
  { match: /金鱗湖|由布院/, page: 'https://www.yufuin.gr.jp/' },
  { match: /海地獄/, page: 'https://www.beppu-jigoku.com/' },
  { match: /血の池/, page: 'https://www.beppu-jigoku.com/' },
  { match: /龍巻地獄|龍卷/, page: 'https://www.beppu-jigoku.com/' },
  { match: /白池地獄/, page: 'https://www.beppu-jigoku.com/' },
  { match: /門司港|門司/, page: 'https://www.mojiko-retro.com/' },
  { match: /関門海峡|關門/, page: 'https://www.kanmon.gr.jp/' },
  { match: /熊本城/, page: 'https://kumamon-official.jp/' },
  { match: /くまモン|熊本熊/, page: 'https://kumamon-official.jp/' },
  { match: /九十九島|佐世保/, page: 'https://www.city.sasebo.lg.jp/' },
  { match: /グラバー|哥拉巴/, page: 'https://www.glover-garden.jp/' },
  { match: /眼鏡橋/, page: 'https://www.nagasaki-tabinet.com/guide/meikyo/' },
  { match: /PALM BEACH|やしの木|糸島|Itoshima/i, page: 'https://palmbeach.jp/' },
  { match: /桜井二見|夫婦岩|二見浦/, page: 'https://www.itoshima-guide.jp/' },
  { match: /芥屋の大門/, page: 'https://www.itoshima-guide.jp/' },
  { match: /大濠公園/, page: 'https://www.ohorikouen.jp/' },
  { match: /福岡タワー|福岡塔/, page: 'https://www.fukuokatower.co.jp/' },
  { match: /ふくや|明太子/, page: 'https://www.fukuya.com/' },
  { match: /一蘭/, page: 'https://www.ichiran.com/' },
  { match: /一風堂|ippudo/i, page: 'https://www.ippudo.com/' },
  { match: /唐戸市場|唐戸/, page: 'https://www.karatoichiba.com/' },
  { match: /柳川|川下り/, page: 'https://www.yanagawa-net.com/' },
  { match: /稲佐山|稻佐/, page: 'https://www.nagasaki-ropeway.jp/' },
  { match: /平和公園|長崎平和/, page: 'https://www.nagasakipeace.jp/' },
  { match: /小倉城/, page: 'https://www.city.kitakyushu.lg.jp/' },
];
